### PR TITLE
Relative path option

### LINKED ISSUE #5: Implement relative paths
tex3pt creates code like this:

```
\estauto{~/foo/my table.tex}
```

Hardcoded paths are not portable. For example, they will not work if the working directory is shared on Dropbox or via version control. I have been manually editing the output to look like this:

```
\estauto{"../my table"}
```

Manually editing is a bear. But it is not easy (or even impossible) to determine how a relative path should be automatically detected, as the file created by tex3pt could be moved around after it is created. I think that there should be some way of specifying a relative path, but I am unsure how.

It could be as simple as an option that allowed the user to specify the `../` bit, but that seems a bit ugly. Maybe it's not as ugly as it looks. I don't know.

A more extreme solution, which would actually suit my workflow, is an option to actually copy the entire contents of the fragment into the file created by tex3pt.

### PR DESCRIPTION
**Pull request by NilsEnevoldsen**
Fixes #5

### CODE REVIEW

**Comment by NilsEnevoldsen** [comment]
Do you not want to pull this feature, or are you waiting for me to resolve the merge conflict?

**Comment by derekwolfson** [comment]
Nils RE: this and many other things you are submitting.  I’ll pull this in shortly, I just need to get on top of work first.

**Comment by NilsEnevoldsen** [comment]
Thanks Derek. No time pressure from my end.

BTW, you might have received several notifications for my recent activity, but at the end of the day there are just two pull requests (and also ~~one~~ two new issues that I haven't touched).

**Comment by derekwolfson** [comment]
Sounds great – I appreciate your help.

**Comment by NilsEnevoldsen** [comment]
This pull request is closed. Merge #27 instead.

**Comment by NilsEnevoldsen** [comment]
:+1:

**Pull request closed without merging**
